name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

    

      - name: 🔨 Install Dependencies
        
        run: |
          npm install
          npm run build
         
      - name:  Sync files
        uses:   SamKirkland/FTP-Deploy-Action@v4.3.0-beta
  
    
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USERNAME }}
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          local-dir: ./dist/
